from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from phd_platform.core.enums import Discipline, GateStatus, Level, Verdict


# ---------------------------------------------------------------------------
# Curriculum models (loaded from YAML)
# ---------------------------------------------------------------------------
class Module(BaseModel):
    id: str
    name: str
    description: str = ""
    objectives: list[str] = []
    textbooks: list[str] = []
    prerequisites: list[str] = []
    assessment: str = ""
    weeks: int = 4
    discipline: Discipline | None = None
    level: Level | None = None


class Gate(BaseModel):
    name: str
    required_score: float | str  # float for mastery, "defense_pass" for doctoral
    format: str = ""
    capstone: str = ""
    panel_size: int = 0
    journals: list[str] = []
    pass_criteria: str = ""


class LevelCurriculum(BaseModel):
    name: str
    description: str = ""
    duration_weeks: str = ""
    gate: Gate
    modules: list[Module] = []
    capstone_description: str = ""


class DisciplineCurriculum(BaseModel):
    name: str
    reference_programs: list[dict] = []
    levels: dict[str, LevelCurriculum] = {}


# ---------------------------------------------------------------------------
# Parsed AI response models
# ---------------------------------------------------------------------------
class DiagnosticQuestion(BaseModel):
    """A single diagnostic question generated by AI."""
    question: str
    type: str = "short_answer"  # mcq, short_answer, proof, computation
    difficulty: int = 3  # 1-5
    objective_index: int = 0
    correct_answer: str = ""
    rubric: str = ""
    partial_credit_criteria: str = ""


class EvaluationResult(BaseModel):
    """AI evaluation of a student's response."""
    score: float  # 0.0 - 1.0
    feedback: str = ""
    weakness_areas: list[str] = []


class CapstoneProposal(BaseModel):
    """A generated capstone project proposal."""
    title: str
    research_question: str = ""
    methodology: str = ""
    data_sources: str = ""
    contribution: str = ""
    milestones: str = ""
    risks: str = ""


class ReviewDimensionScore(BaseModel):
    """Score for a single review dimension."""
    dimension: str
    score: int  # 1-5
    issues: list[str] = []
    suggestions: list[str] = []


class PreDefenseReview(BaseModel):
    """Structured pre-defense review of a capstone paper."""
    dimension_scores: list[ReviewDimensionScore] = []
    overall_assessment: str = ""  # READY, NEEDS REVISION, NOT READY
    predicted_questions: list[str] = []
    summary: str = ""


class VerdictResult(BaseModel):
    """Structured verdict from a defense reviewer."""
    verdict: str  # Accept, Minor Revision, Major Revision, Reject
    justification: str = ""
    strengths: list[str] = []
    weaknesses: list[str] = []
    suggestions: list[str] = []


# ---------------------------------------------------------------------------
# Student progress models
# ---------------------------------------------------------------------------
class ModuleScore(BaseModel):
    module_id: str
    score: float  # 0.0 - 1.0
    attempts: int = 1
    completed_at: datetime | None = None
    weakness_areas: list[str] = []


class CapstoneSubmission(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    title: str
    abstract: str = ""
    submitted_at: datetime = Field(default_factory=datetime.now)
    revision_number: int = 0


class DefenseResult(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    capstone_id: UUID
    level: Level
    reviewer_verdicts: dict[str, Verdict] = {}  # journal_name -> verdict
    overall_pass: bool = False
    feedback: dict[str, str] = {}  # journal_name -> detailed feedback
    conducted_at: datetime = Field(default_factory=datetime.now)

    @property
    def passing_count(self) -> int:
        return sum(1 for v in self.reviewer_verdicts.values() if v.is_passing)

    @property
    def revision_count(self) -> int:
        return sum(1 for v in self.reviewer_verdicts.values() if v.allows_resubmission)


class Progress(BaseModel):
    discipline: Discipline
    current_level: Level = Level.FOUNDATION
    module_scores: dict[str, ModuleScore] = {}
    gate_statuses: dict[str, GateStatus] = {}  # level -> status
    capstones: list[CapstoneSubmission] = []
    defenses: list[DefenseResult] = []

    @property
    def current_mastery(self) -> float:
        """Average mastery across all modules in the current level."""
        level_scores = [
            s.score for s in self.module_scores.values()
            if s.module_id.split("-")[1][0] == self.current_level.value[0].upper()
        ]
        return sum(level_scores) / len(level_scores) if level_scores else 0.0

    @property
    def weakness_modules(self) -> list[str]:
        """Modules scoring below 80% that need remediation."""
        return [
            s.module_id for s in self.module_scores.values()
            if s.score < 0.80
        ]


class Student(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    name: str
    email: str = ""
    interests: list[str] = []
    strengths: list[str] = []
    enrolled_disciplines: list[Discipline] = []
    progress: dict[str, Progress] = {}  # discipline -> progress
    created_at: datetime = Field(default_factory=datetime.now)

    def get_progress(self, discipline: Discipline) -> Progress:
        key = discipline.value
        if key not in self.progress:
            self.progress[key] = Progress(discipline=discipline)
        return self.progress[key]
